=== globallightingdata/l3d/xsd/l3d.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
	<xs:element name="Luminaire" type="LuminaireDataType">
		<xs:key name="GeometryReferenceId">
			<xs:selector xpath="GeometryDefinitions/GeometryFileDefinition" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:keyref name="GeometrySourceFileReference" refer="GeometryReferenceId">
			<xs:selector xpath=".//GeometryReference" />
			<xs:field xpath="@geometryId" />
		</xs:keyref>
		<xs:key name="LightEmittingPartName">
			<xs:selector xpath=".//LightEmittingObject" />
			<xs:field xpath="@partName" />
		</xs:key>
		<xs:unique name="UniquePartName">
			<xs:selector xpath=".//Geometry|.//Joint|.//LightEmittingObject" />
			<xs:field xpath="@partName"></xs:field>
		</xs:unique>
		<xs:keyref name="LightEmittingPartReferenceInLightEmittingSurface" refer="LightEmittingPartName">
			<xs:selector xpath=".//LightEmittingObjectReference" />
			<xs:field xpath="@lightEmittingPartName" />
		</xs:keyref>
	</xs:element>
	<xs:complexType name="LuminaireDataType">
		<xs:sequence>
			<xs:element name="Header" minOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Name" type="xs:string" minOccurs="0" />
						<xs:element name="Description" type="xs:string" minOccurs="0" />
						<xs:element name="CreatedWithApplication" type="xs:string" minOccurs="1" />
						<xs:element name="CreationTimeCode" type="xs:dateTime" minOccurs="1" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="GeometryDefinitions" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element name="GeometryFileDefinition">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="GeometricFileData">
											<xs:attribute name="id" type="xs:NCName" use="required" />
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Structure">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Geometry" type="GeometryNodeType" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GeometryNodeType">
		<xs:complexContent>
			<xs:extension base="TransformableNodeType">
				<xs:sequence>
					<xs:element ref="GeometrySource" minOccurs="1" maxOccurs="1" />
					<xs:element name="Joints" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Joint" type="JointNodeType" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="LightEmittingObjects" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="LightEmittingObject" maxOccurs="unbounded">
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="LightEmittingNodeType" />
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="SensorObjects" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="SensorObject" maxOccurs="unbounded">
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="TransformableNodeType" />
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="LightEmittingSurfaces" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="LightEmittingSurface" maxOccurs="unbounded">
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="LightEmittingSurfaceNodeType" />
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="ElectricalConnectors" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="ElectricalConnector" type="VectorType" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="PendulumConnectors" minOccurs="0">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="PendulumConnector" type="VectorType" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="includedInMeasurement" type="xs:boolean" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="JointNodeType">
		<xs:complexContent>
			<xs:extension base="TransformableNodeType">
				<xs:sequence>
					<xs:element name="XAxis" type="AxisRotationType" minOccurs="0" />
					<xs:element name="YAxis" type="AxisRotationType" minOccurs="0" />
					<xs:element name="ZAxis" type="AxisRotationType" minOccurs="0" />
					<xs:element name="DefaultRotation" type="VectorType" minOccurs="0" maxOccurs="1" />
					<xs:element name="Geometries" minOccurs="1" maxOccurs="1">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Geometry" type="GeometryNodeType" minOccurs="1" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:element name="LightEmittingFaceAssignmentType" abstract="true"></xs:element>
	<xs:element name="FaceAssignment" substitutionGroup="LightEmittingFaceAssignmentType">
		<xs:complexType>
			<xs:attribute name="groupIndex" type="xs:int" use="optional" />
			<xs:attribute name="faceIndex" type="xs:int" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="FaceRangeAssignment" substitutionGroup="LightEmittingFaceAssignmentType">
		<xs:complexType>
			<xs:attribute name="groupIndex" type="xs:int" use="optional" />
			<xs:attribute name="faceIndexBegin" type="xs:int" use="required" />
			<xs:attribute name="faceIndexEnd" type="xs:int" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:complexType name="NodeType">
		<xs:attribute name="partName" type="xs:NCName" use="required" />
	</xs:complexType>
	<xs:complexType name="ColorType">
		<xs:attribute name="r" type="xs:double" />
		<xs:attribute name="g" type="xs:double" />
		<xs:attribute name="b" type="xs:double" />
	</xs:complexType>
	<xs:complexType name="TransformableNodeType">
		<xs:complexContent>
			<xs:extension base="NodeType">
				<xs:sequence>
					<xs:element name="Position" type="VectorType" minOccurs="1" maxOccurs="1" />
					<xs:element name="Rotation" type="VectorType" minOccurs="1" maxOccurs="1" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="VectorType">
		<xs:attribute name="x" type="xs:double" use="required" />
		<xs:attribute name="y" type="xs:double" use="required" />
		<xs:attribute name="z" type="xs:double" use="required" />
	</xs:complexType>
	<xs:complexType name="AxisRotationType">
		<xs:attribute name="min" type="xs:double" use="required" />
		<xs:attribute name="max" type="xs:double" use="required" />
		<xs:attribute name="step" type="xs:double" use="required" />
	</xs:complexType>
	<xs:complexType name="LightEmittingNodeType">
		<xs:complexContent>
			<xs:extension base="TransformableNodeType">
				<xs:sequence>
					<xs:element ref="ShapeType" />
					<xs:element name="LuminousHeights" minOccurs="0" maxOccurs="1">
						<xs:complexType>
							<xs:attribute name="c0" type="xs:double" use="required" />
							<xs:attribute name="c90" type="xs:double" use="required" />
							<xs:attribute name="c180" type="xs:double" use="required" />
							<xs:attribute name="c270" type="xs:double" use="required" />
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="LightEmittingSurfaceNodeType">
		<xs:complexContent>
			<xs:extension base="NodeType">
				<xs:sequence>
					<xs:element name="LightEmittingObjectReference" minOccurs="1" maxOccurs="unbounded">
						<xs:complexType>
							<xs:attribute name="lightEmittingPartName" type="xs:NCName" use="required" />
							<xs:attribute name="intensity" type="xs:double" use="optional" />
						</xs:complexType>
					</xs:element>
					<xs:element name="FaceAssignments">
						<xs:complexType>
							<xs:sequence>
								<xs:element ref="LightEmittingFaceAssignmentType" minOccurs="1" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="ShapeType" abstract="true" />
	<xs:element name="Circle" substitutionGroup="ShapeType">
		<xs:complexType>
			<xs:attribute name="diameter" type="xs:double" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="Rectangle" substitutionGroup="ShapeType">
		<xs:complexType>
			<xs:attribute name="sizeX" type="xs:double" use="required" />
			<xs:attribute name="sizeY" type="xs:double" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="GeometryUnitsType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="m" />
			<xs:enumeration value="mm" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="GeometryDataType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="base64/obj" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="GeometricFileData">
		<xs:attribute name="filename" type="xs:string" use="required" />
		<xs:attribute name="units" type="GeometryUnitsType" use="required" />
	</xs:complexType>
	<xs:element name="GeometrySource" abstract="true" />
	<xs:element name="GeometryReference" substitutionGroup="GeometrySource">
		<xs:complexType>
			<xs:attribute name="geometryId" type="xs:NCName" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== globallightingdata/l3d/examples/example_002/structure.xml
<?xml version="1.0" encoding="UTF-8"?>
<Luminaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/l3d.xsd">
    <Header>
        <Name>First example</Name>
        <Description>First ever xml luminaire geometry description</Description>
        <CreatedWithApplication>Keyboard-v1.0</CreatedWithApplication>
        <CreationTimeCode>2020-12-03T16:33:44</CreationTimeCode>
    </Header>
    <GeometryDefinitions>
        <GeometryFileDefinition id="base" filename="base.obj" units="mm" />
        <GeometryFileDefinition id="base-arm-con" filename="base-arm-con.obj" units="mm" />
        <GeometryFileDefinition id="arm" filename="arm.obj" units="mm" />
        <GeometryFileDefinition id="arm-head-con" filename="arm-head-con.obj" units="mm" />
        <GeometryFileDefinition id="head" filename="head.obj" units="mm" />
    </GeometryDefinitions>
    <Structure>
        <Geometry partName="base">
            <Position x="0" y="0" z="0" />
            <Rotation x="0" y="0" z="0" />
            <GeometryReference geometryId="base" />
            <Joints>
                <Joint partName="base-con-hinge">
                    <Position x="0" y="0.05" z="0.05" />
                    <Rotation x="0" y="0" z="0" />
                    <ZAxis min="-15" max="15" step="1" />
                    <Geometries>
                        <Geometry partName="base-arm-con">
                            <Position x="0" y="-0.05" z="-0.05" />
                            <Rotation x="0" y="0" z="0" />
                            <GeometryReference geometryId="base-arm-con" />
                            <Joints>
                                <Joint partName="con-arm-hinge">
                                    <Position x="0" y="0.05" z="0.085" />
                                    <Rotation x="0" y="0" z="0" />
                                    <XAxis min="0" max="60" step="1" />
                                    <DefaultRotation x="30" y="0" z="0" />
                                    <Geometries>
                                        <Geometry partName="arm">
                                            <Position x="0" y="-0.05" z="-0.085" />
                                            <Rotation x="0" y="0" z="0" />
                                            <GeometryReference geometryId="arm" />
                                            <Joints>
                                                <Joint partName="arm-con-hinge">
                                                    <Position x="0" y="0.05" z="0.485" />
                                                    <Rotation x="90" y="0" z="0" />
                                                    <XAxis min="-60" max="0" step="1" />
                                                    <DefaultRotation x="-30" y="0" z="0" />
                                                    <Geometries>
                                                        <Geometry partName="arm-head-con">
                                                            <Position x="0" y="-0.05" z="-0.485" />
                                                            <Rotation x="0" y="0" z="0" />
                                                            <GeometryReference geometryId="arm-head-con" />
                                                            <Joints>
                                                                <Joint partName="con-head-hinge">
                                                                    <Position x="0" y="0.05" z="0.525" />
                                                                    <Rotation x="0" y="0" z="0" />
                                                                    <ZAxis min="-15" max="15" step="1" />
                                                                    <Geometries>
                                                                        <Geometry partName="head" excludedFromMeasurement="true">
                                                                            <Position x="0" y="-0.05" z="-0.525" />
                                                                            <Rotation x="0" y="0" z="0" />
                                                                            <GeometryReference geometryId="head" />
                                                                            <LightEmittingObjects>
                                                                                <LightEmittingObject partName="leo">
                                                                                    <Position x="0" y="0.04631" z="0.6771" />
                                                                                    <Rotation x="90" y="0" z="180" />
                                                                                    <Rectangle sizeX="0.18" sizeY="0.08" />
                                                                                </LightEmittingObject>
                                                                            </LightEmittingObjects>
                                                                            <LightEmittingSurfaces>
                                                                                <LightEmittingSurface partName="les">
                                                                                    <LightEmittingObjectReference lightEmittingPartName="leo" />
                                                                                    <FaceAssignments>
                                                                                        <FaceAssignment faceIndex="16" />
                                                                                        <FaceAssignment faceIndex="17" />
                                                                                        <FaceAssignment faceIndex="18" />
                                                                                        <FaceRangeAssignment faceIndexBegin="19" faceIndexEnd="21" />
                                                                                    </FaceAssignments>
                                                                                </LightEmittingSurface>
                                                                            </LightEmittingSurfaces>
                                                                        </Geometry>
                                                                    </Geometries>
                                                                </Joint>
                                                            </Joints>
                                                        </Geometry>
                                                    </Geometries>
                                                </Joint>
                                            </Joints>
                                        </Geometry>
                                    </Geometries>
                                </Joint>
                            </Joints>
                        </Geometry>
                    </Geometries>
                </Joint>
            </Joints>
        </Geometry>
    </Structure>
</Luminaire>

=== globallightingdata/l3d/examples/example_005/structure.xml
<?xml version="1.0" encoding="UTF-8"?>
<Luminaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/l3d.xsd">
    <Header>
        <Name>Another example</Name>
        <Description>Example luminaire 4</Description>
        <CreatedWithApplication>Keyboard-v1.0</CreatedWithApplication>
        <CreationTimeCode>2021-01-07T16:33:44</CreationTimeCode>
    </Header>
    <GeometryDefinitions>
        <GeometryFileDefinition id="base" filename="base.obj" units="mm" />
        <GeometryFileDefinition id="head" filename="head.obj" units="mm" />
    </GeometryDefinitions>
    <Structure>
        <Geometry partName="base">
            <Position x="0" y="0" z="0" />
            <Rotation x="0" y="0" z="0" />
            <GeometryReference geometryId="base" />
            <Joints>
                <Joint partName="head-hinge">
                    <Position x="0" y="0" z="0.5" />
                    <Rotation x="45" y="0" z="0" />
                    <ZAxis min="-30" max="30" step="1" />
                    <Geometries>
                        <Geometry partName="head" includedInMeasurement="false">
                            <Position x="0" y="-0.3535" z="-0.3535" />
                            <Rotation x="-45" y="0" z="0" />
                            <GeometryReference geometryId="head" />
                            <LightEmittingObjects>
                                <LightEmittingObject partName="leo">
                                    <Position x="0" y="-0.064" z="0.475" />
                                    <Rotation x="-45" y="0" z="0" />
                                    <Rectangle sizeX="0.15" sizeY="0.035" />
                                </LightEmittingObject>
                            </LightEmittingObjects>
                            <LightEmittingSurfaces>
                                <LightEmittingSurface partName="les">
                                    <LightEmittingObjectReference lightEmittingPartName="leo" />
                                    <FaceAssignments>
                                        <FaceRangeAssignment faceIndexBegin="158" faceIndexEnd="179" />
                                    </FaceAssignments>
                                </LightEmittingSurface>
                            </LightEmittingSurfaces>
                        </Geometry>
                    </Geometries>
                </Joint>
            </Joints>
        </Geometry>
    </Structure>
</Luminaire>

=== globallightingdata/l3d/examples/example_003/structure.xml
<?xml version="1.0" encoding="UTF-8"?>
<Luminaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/l3d.xsd">
    <Header>
        <CreatedWithApplication>Keyboard-v1.0</CreatedWithApplication>
        <CreationTimeCode>2020-12-11T11:12:13</CreationTimeCode>
    </Header>
    <GeometryDefinitions>
        <GeometryFileDefinition id="luminaire" filename="luminaire.obj" units="mm" />
    </GeometryDefinitions>
    <Structure>
        <Geometry partName="luminaire">
            <Position x="0" y="0" z="0" />
            <Rotation x="0" y="0" z="0" />
            <GeometryReference geometryId="luminaire" />
            <LightEmittingObjects>
                <LightEmittingObject partName="leo">
                    <Position x="0" y="0" z="0" />
                    <Rotation x="0" y="0" z="0" />
                    <Circle diameter="0.1" />
                </LightEmittingObject>
            </LightEmittingObjects>
            <LightEmittingSurfaces>
                <LightEmittingSurface partName="les">
                    <LightEmittingObjectReference lightEmittingPartName="leo" />
                    <FaceAssignments>
                        <FaceRangeAssignment faceIndexBegin="1199" faceIndexEnd="1235" />
                    </FaceAssignments>
                </LightEmittingSurface>
            </LightEmittingSurfaces>
        </Geometry>
    </Structure>
</Luminaire>

=== globallightingdata/l3d/examples/example_000/structure.xml
<?xml version="1.0" encoding="UTF-8"?>
<Luminaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://gldf.io/xsd/l3d/0.11.0/l3d.xsd">
    <Header>
        <CreatedWithApplication>Example-Tool</CreatedWithApplication>
        <CreationTimeCode>2021-03-03T10:10:10</CreationTimeCode>
        <FormatVersion major="0" minor="11" />
    </Header>
    <GeometryDefinitions>
        <GeometryFileDefinition id="cube" filename="cube.obj" units="m" />
    </GeometryDefinitions>
    <Structure>
        <Geometry partName="luminaire" includedInMeasurement="true">
            <Position x="0" y="0" z="0" />
            <Rotation x="0" y="0" z="0" />
            <GeometryReference geometryId="cube" />
            <LightEmittingObjects>
                <LightEmittingObject partName="leo">
                    <Position x="0" y="0" z="0" />
                    <Rotation x="0" y="0" z="0" />
                    <Rectangle sizeX="0.5" sizeY="0.25" />
                </LightEmittingObject>
            </LightEmittingObjects>
            <LightEmittingSurfaces>
                <LightEmittingSurface partName="les">
                    <LightEmittingObjectReference lightEmittingPartName="leo" />
                    <FaceAssignments>
                        <FaceAssignment faceIndex="3" />
                    </FaceAssignments>
                </LightEmittingSurface>
            </LightEmittingSurfaces>
        </Geometry>
    </Structure>
</Luminaire>

=== globallightingdata/l3d/examples/example_004/structure.xml
<?xml version="1.0" encoding="UTF-8"?>
<Luminaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://gldf.io/xsd/l3d/0.11.0/l3d.xsd">
    <Header>
        <CreatedWithApplication>Keyboard-v1.0</CreatedWithApplication>
        <CreationTimeCode>2020-12-11T11:12:13</CreationTimeCode>
        <FormatVersion major="0" minor="11" />
    </Header>
    <GeometryDefinitions>
        <GeometryFileDefinition id="luminaire" filename="luminaire.obj" units="mm" />
    </GeometryDefinitions>
    <Structure>
        <Geometry partName="luminaire">
            <Position x="0" y="0" z="-0.5" />
            <Rotation x="0" y="0" z="0" />
            <GeometryReference geometryId="luminaire" />
            <LightEmittingObjects>
                <LightEmittingObject partName="leo_top">
                    <Position x="0" y="0" z="0.0375" />
                    <Rotation x="180" y="0" z="90" />
                    <Rectangle sizeX="0.15" sizeY="1" />
                </LightEmittingObject>
                <LightEmittingObject partName="leo_bottom">
                    <Position x="0" y="0" z="0.0025" />
                    <Rotation x="0" y="0" z="-90" />
                    <Rectangle sizeX="0.17" sizeY="1.175" />
                </LightEmittingObject>
            </LightEmittingObjects>
            <LightEmittingSurfaces>
                <LightEmittingSurface partName="les_bottom">
                    <LightEmittingObjectReference lightEmittingPartName="leo_bottom" />
                    <FaceAssignments>
                        <FaceAssignment faceIndex="90" />
                        <FaceAssignment faceIndex="91" />
                    </FaceAssignments>
                </LightEmittingSurface>
                <LightEmittingSurface partName="les_top">
                    <LightEmittingObjectReference lightEmittingPartName="leo_top" />
                    <FaceAssignments>
                        <FaceAssignment faceIndex="84" />
                        <FaceAssignment faceIndex="85" />
                    </FaceAssignments>
                </LightEmittingSurface>
            </LightEmittingSurfaces>
            <ElectricalConnectors>
                <ElectricalConnector x="-0.575" y="0" z="0.04" />
            </ElectricalConnectors>
            <PendulumConnectors>
                <PendulumConnector x="-0.55" y="0" z="0.04" />
                <PendulumConnector x="0.55" y="0" z="0.04" />
            </PendulumConnectors>
        </Geometry>
    </Structure>
</Luminaire>

=== globallightingdata/l3d/examples/example_001/structure.xml
<?xml version="1.0" encoding="UTF-8"?>
<Luminaire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/globallightingdata/l3d/develop/xsd/l3d.xsd">
	<Header>
		<CreatedWithApplication>Example-Tool</CreatedWithApplication>
		<CreationTimeCode>2021-03-03T10:10:10</CreationTimeCode>
	</Header>
	<GeometryDefinitions>
		<GeometryFileDefinition id="cube" filename="cube.obj" units="m" />
	</GeometryDefinitions>
	<Structure>
		<Geometry partName="luminaire">
			<Position x="-0.25" y="-0.125" z="0.05" />
			<Rotation x="0" y="0" z="0" />
			<GeometryReference geometryId="cube" />
			<LightEmittingObjects>
				<LightEmittingObject partName="leo">
					<Position x="0.25" y="0.125" z="-0.05" />
					<Rotation x="0" y="0" z="0" />
					<Rectangle sizeX="0.5" sizeY="0.25" />
				</LightEmittingObject>
			</LightEmittingObjects>
			<LightEmittingFaceAssignments>
				<Assignment faceIndex="3" lightEmittingPartName="leo" />
			</LightEmittingFaceAssignments>
		</Geometry>
	</Structure>
</Luminaire>
